<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

abstract class AbstractUser extends Model
{
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'bigInteger';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
    
    public function roles()
    {
        return $this->belongsToMany('\App\Models\Role', 'user_role', 'user_id', 'role_id')
            ->withPivot('id', 'created_at', 'updated_at');
    }
    
    public function etablissements()
    {
        return $this->belongsToMany('\App\Models\Etablissement', 'user_etablissement', 'user_id', 'etablissement_id')
            ->withPivot('id', 'created_at', 'updated_at');
    }
}
